version: '3.8'
services:
  #Laravel Service
  laravelapp:
    build:
      context: ../laravelApplication/
      dockerfile: Dockerfile
    container_name: laravelapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravelApplication
    volumes:
      - ../laravelApplication/:/var/www/laravelApplication
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravelapp-network
  #Nginx Service
  laravelapp-nginx:
    image: nginx
    container_name: laravelapp-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "5050:80"
    #      - "443:443"
    volumes:
      - ../laravelApplication/:/var/www/laravelApplication
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravelapp-network


  #MySQL Service
  laravelapp-mysql:
    image: mysql
    container_name: laravelapp-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravelapp
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - laravelapp-network
#Docker Networks
networks:
  laravelapp-network:
    driver: bridge
#Volumes
volumes:
  laravelapp-mysql:
    driver: local
